/* ============================================================
   STAR TRADER — digital adaptation of Paul Elliott's solo game.
   Trade, world-gen, ship costs & crew use the Cepheus Engine SRD
   (Open Game Content, OGL 1.0a — Samardan Press). The d66 World /
   Port / Jump event tables are from Star Trader (Zozer Games).
   ============================================================ */

const R = (n=6)=>Math.floor(Math.random()*n)+1;          // d-n
const d6 = ()=>R(6);
const d66 = ()=>d6()*10+d6();
const _2d6 = ()=>d6()+d6();
const ehex = v=>{ v=Math.max(0,Math.round(v)); return v<10?String(v):String.fromCharCode(55+v); };
const cr = n=>{ const s=Math.abs(Math.round(n)).toLocaleString('en-US'); return (n<0?'-Cr':'Cr')+s; };

/* ---------- Trade-goods table (Cepheus Engine SRD, OGC) ---------- */
// Cepheus "Trade and Commerce" (Ch.7). Availability is by random D66 roll, NOT
// by trade code; trade codes only drive price. pDM = Purchase DMs (world makes it
// cheap), rDM = Sale DMs (world wants it). Only the LARGEST DM in each column
// applies, and the opposing column subtracts. tons = dice spec rolled at market.
const COMMON = [                         // always available from any supplier
 {id:101,name:'Basic Consumables',        base:1000,   tons:'2D6*5', pDM:{}, rDM:{}},
 {id:102,name:'Basic Electronics',        base:25000,  tons:'2D6*5', pDM:{}, rDM:{}},
 {id:103,name:'Basic Machine Parts',      base:10000,  tons:'2D6*5', pDM:{}, rDM:{}},
 {id:104,name:'Basic Manufactured Goods', base:20000,  tons:'2D6*5', pDM:{}, rDM:{}},
 {id:105,name:'Basic Raw Materials',      base:5000,   tons:'2D6*5', pDM:{}, rDM:{}},
 {id:106,name:'Basic Unrefined Ore',      base:2000,   tons:'2D6*5', pDM:{}, rDM:{}},
];
const TRADE = {                          // D66-keyed Trade Goods
 11:{id:11,name:'Advanced Electronics',      base:100000, tons:'1D6*5', pDM:{Ht:2,In:3}, rDM:{Ni:2,Po:1}},
 12:{id:12,name:'Advanced Manufactured Goods',base:200000,tons:'1D6*5', pDM:{In:3,Ri:2}, rDM:{Ag:1,Ni:2}},
 13:{id:13,name:'Agricultural Equipment',    base:150000, tons:'1D6',   pDM:{In:3,Ri:2}, rDM:{Ag:2,Ga:1}},
 14:{id:14,name:'Animal Products',           base:1500,   tons:'4D6*5', pDM:{Ag:2,Ga:3}, rDM:{Hi:2,Ri:1}},
 15:{id:15,name:'Collectibles',              base:50000,  tons:'1D6',   pDM:{In:2,Ri:3}, rDM:{Hi:2,Ni:1}},
 16:{id:16,name:'Computers & Parts',         base:150000, tons:'2D6',   pDM:{Ht:3,In:2}, rDM:{Na:1,Ni:2}},
 21:{id:21,name:'Crystals & Gems',           base:20000,  tons:'1D6*5', pDM:{Ni:3,Na:2}, rDM:{In:1,Ri:2}},
 22:{id:22,name:'Cybernetic Parts',          base:250000, tons:'1D6*5', pDM:{Ht:3,Ri:2}, rDM:{Na:1,Ni:2}},
 23:{id:23,name:'Food Service Equipment',    base:4000,   tons:'2D6',   pDM:{In:3,Na:2}, rDM:{Ag:1,Ni:2}},
 24:{id:24,name:'Furniture',                 base:5000,   tons:'4D6',   pDM:{Ag:2,Ga:3}, rDM:{Hi:1,Ri:2}},
 25:{id:25,name:'Gambling Devices',          base:4000,   tons:'1D6',   pDM:{Hi:2,Ri:3}, rDM:{Na:2,Ni:1}},
 26:{id:26,name:'Grav Vehicles',             base:160000, tons:'1D6',   pDM:{Ht:3,Ri:2}, rDM:{Ni:2,Po:1}},
 31:{id:31,name:'Grocery Products',          base:6000,   tons:'1D6*5', pDM:{Ag:3,Ga:2}, rDM:{Hi:1,Ri:2}},
 32:{id:32,name:'Household Appliances',      base:12000,  tons:'4D6',   pDM:{Hi:2,In:3}, rDM:{Na:1,Ni:2}},
 33:{id:33,name:'Industrial Supplies',       base:75000,  tons:'2D6',   pDM:{In:3,Ri:2}, rDM:{Na:1,Ni:2}},
 34:{id:34,name:'Liquor & Intoxicants',      base:15000,  tons:'1D6*5', pDM:{Ag:3,Ga:2}, rDM:{In:1,Ri:2}},
 35:{id:35,name:'Luxury Goods',              base:150000, tons:'1D6',   pDM:{Ag:2,Ga:3}, rDM:{In:1,Ri:2}},
 36:{id:36,name:'Manufacturing Equipment',   base:750000, tons:'1D6*5', pDM:{In:3,Ri:2}, rDM:{Na:1,Ni:2}},
 41:{id:41,name:'Medical Equipment',         base:50000,  tons:'1D6*5', pDM:{Ht:2,Ri:3}, rDM:{Hi:1,In:2}},
 42:{id:42,name:'Petrochemicals',            base:10000,  tons:'2D6*5', pDM:{Na:2,Ni:3}, rDM:{Ag:1,In:2}},
 43:{id:43,name:'Pharmaceuticals',           base:100000, tons:'1D6',   pDM:{Ht:3,Wa:2}, rDM:{In:2,Ri:1}},
 44:{id:44,name:'Polymers',                  base:7000,   tons:'4D6*5', pDM:{In:2,Ri:3}, rDM:{Ni:2,Va:1}},
 45:{id:45,name:'Precious Metals',           base:50000,  tons:'1D6',   pDM:{As:3,Ic:2}, rDM:{In:1,Ri:2}},
 46:{id:46,name:'Radioactives',              base:1000000,tons:'1D6',   pDM:{As:2,Ni:3}, rDM:{In:2,Ht:1}},
 51:{id:51,name:'Robots & Drones',           base:500000, tons:'1D6*5', pDM:{Ht:3,In:2}, rDM:{Ni:1,Ri:2}},
 52:{id:52,name:'Scientific Equipment',      base:50000,  tons:'1D6*5', pDM:{Ht:3,Ri:2}, rDM:{Hi:2,Ni:1}},
 53:{id:53,name:'Survival Gear',             base:4000,   tons:'2D6',   pDM:{Ga:3,Ri:2}, rDM:{Fl:2,Va:1}},
 54:{id:54,name:'Textiles',                  base:3000,   tons:'3D6*5', pDM:{Ag:3,Ni:2}, rDM:{Na:1,Ri:2}},
 55:{id:55,name:'Uncommon Raw Materials',    base:50000,  tons:'2D6*5', pDM:{Ag:3,Ni:2}, rDM:{In:2,Na:1}},
 56:{id:56,name:'Uncommon Unrefined Ores',   base:20000,  tons:'2D6*5', pDM:{As:2,Va:1}, rDM:{In:2,Na:1}},
 61:{id:61,name:'Illicit Luxury Goods',      base:150000, tons:'1D6',   pDM:{Ag:2,Ga:3}, rDM:{In:4,Ri:6}, illegal:true},
 62:{id:62,name:'Illicit Pharmaceuticals',   base:100000, tons:'1D6',   pDM:{Ht:3,Wa:2}, rDM:{In:6,Ri:4}, illegal:true},
 63:{id:63,name:'Medical Research Material',  base:50000,  tons:'1D6*5', pDM:{Ht:2,Ri:3}, rDM:{In:6,Na:4}, illegal:true},
 64:{id:64,name:'Military Equipment',        base:150000, tons:'2D6',   pDM:{Ht:3,In:2}, rDM:{Hi:6,Ni:4}, illegal:true},
 65:{id:65,name:'Personal Weapons & Armor',  base:30000,  tons:'2D6',   pDM:{In:3,Ri:2}, rDM:{Ni:6,Po:4}, illegal:true},
};
const ALLGOODS={}; COMMON.forEach(g=>ALLGOODS[g.id]=g); Object.values(TRADE).forEach(g=>ALLGOODS[g.id]=g);
const ILLEGAL_GOODS=Object.values(TRADE).filter(g=>g.illegal);

// Specific thematic goods, 50 per category. The category (good "type") keeps all
// the mechanics — base price, DMs, tonnage dice; the variant name is pure flavour,
// rolled when a lot reaches the market. Display shows variant + type.
const GOODNAMES={
101:['Vat-Grown Protein Blocks','Dehydrated Ration Packs','Recycled Water Tanks','Nutrient Paste Crates','Long-Store Grain Meal',
 'Synth-Caf Tins','Pressed Algae Cakes','Emergency Meal Kits','Fortified Biscuit Pallets','Soy Substitute Bricks',
 'Powdered Milk Drums','Iodized Salt Sacks','Cooking Oil Drums','Freeze-Dried Vegetables','Canned Fish Analog',
 'Yeast Culture Vats','Sugar Syrup Totes','Flour Silo Bags','Instant Soup Cartons','Electrolyte Drink Mix',
 'Shipboard Tea Chests','Pickled Produce Jars','Starch Tuber Crates','Dry Bean Sacks','Cube Sugar Cases',
 'Hardtack Crates','Protein Jerky Strips','Vitamin Tablet Drums','Filtered Water Pouches','Brewing Yeast Packs',
 'Mess-Hall Coffee Drums','Sterile Food Wrap Rolls','Field Stove Fuel Gel','Soap Bar Pallets','Disinfectant Jugs',
 'Toiletry Kits','Paper Goods Bales','Matchstick Cartons','Candle Wax Blocks','Basic Spice Assortment',
 'Frontier Flour Mix','Dried Fruit Bricks','Egg Powder Tins','Meal Replacement Bars','Trail Mix Drums',
 'Grey-Water Filter Packs','Sterilized Utensil Packs','Bulk Oatmeal Sacks','Honey Substitute Jars','Galley Starter Kits'],
102:['Handheld Comm Units','Budget Vid Displays','Circuit Board Bundles','Power Cell Crates','Wire Spool Pallets',
 'Portable Radio Sets','Door Sensor Kits','Light Panel Cartons','Basic Drone Controllers','Audio Bead Earpieces',
 'Battery Charger Racks','Signal Booster Boxes','Cheap Hand Scanners','Alarm Klaxon Units','Switchboard Relays',
 'Fuse Assortment Tins','Cable Harness Kits','Personal Torch Lamps','Desk Terminal Shells','Keypad Lock Sets',
 'Intercom Wall Units','Surge Protector Strips','Microphone Pencils','Speaker Cone Crates','Antenna Whip Bundles',
 'Thermostat Modules','Motion Detector Pucks','Soldering Kit Cases','Diagnostic Multimeters','Timer Switch Boxes',
 'Smoke Sensor Discs','Voltage Converter Bricks','Hobby Servo Packs','Indicator Lamp Reels','Remote Control Fobs',
 'Static Memory Sticks','Vid Cable Spools','Headlamp Sets','Field Telephone Pairs','Beacon Strobe Lights',
 'Transistor Grab Bags','Capacitor Barrels','Relay Coil Crates','Dashboard Gauge Sets','Clip-On Fan Units',
 'Entry Chime Kits','Glow Strip Rolls','Watch Movement Trays','Calculator Slabs','Spare Remote Boards'],
103:['Bearing Race Crates','Gasket Assortments','Bolt and Nut Kegs','Drive Belt Loops','Gear Blank Pallets',
 'Hydraulic Seal Kits','Valve Body Castings','Pump Impeller Sets','Piston Ring Cases','Camshaft Blanks',
 'Coupler Sleeve Boxes','Spring Steel Coils','Axle Rod Bundles','Filter Cartridge Drums','Brake Pad Stacks',
 'Chain Link Reels','Pulley Wheel Crates','Shim Stock Sheets','Bushing Trays','Clutch Plate Cartons',
 'Welding Rod Tubes','Thread Tap Sets','Lathe Tool Bits','Grinder Disc Packs','Drill Bit Indexes',
 'O-Ring Assortment Tins','Hose Clamp Barrels','Pipe Fitting Kegs','Flange Plate Stacks','Anchor Bolt Crates',
 'Torsion Bar Bundles','Sprocket Sets','Roller Chain Drums','Fastener Grab Pallets','Lubricant Grease Kegs',
 'Compressor Reed Kits','Injector Nozzle Trays','Turnbuckle Cases','Wire Rope Spools','Leaf Spring Packs',
 'Universal Joint Boxes','Mounting Bracket Bales','Sheave Block Crates','Key Stock Bars','Retaining Clip Jars',
 'Machinist Vise Sets','Caliper Tool Rolls','Press Die Blanks','Repair Plate Steel','Manifold Castings'],
104:['Stamped Cookware Sets','Work Boot Cases','Plastic Furniture Flats','Hand Tool Rolls','Storage Drum Nests',
 'Window Glass Panes','Ceramic Tile Pallets','Rope and Twine Bales','Canvas Tarp Bundles','Garden Tool Bundles',
 'Padlock Crates','Sewing Machine Heads','Bicycle Frame Kits','Water Pump Handsets','Kerosene Lantern Cases',
 'Steel Shelving Flats','Door Hinge Kegs','Wheelbarrow Kits','Bucket and Basin Nests','Hand Cart Frames',
 'Razor Blade Cartons','Cutlery Service Sets','Stove Top Kettles','Washboard Crates','Utility Knife Boxes',
 'Folding Cot Frames','Insulated Flask Cases','Rain Slicker Bales','Work Glove Bundles','Safety Helmet Stacks',
 'Oil Lamp Chimneys','Pressure Cooker Pots','Meat Grinder Heads','Field Shovel Bundles','Hatchet and Axe Crates',
 'Nail Keg Pallets','Paint Drum Lots','Brush and Roller Kits','Sandpaper Reams','Glue Pot Cases',
 'Clock Spring Movements','Umbrella Bundles','Footlocker Trunks','Mess Kit Cartons','Thermo Jug Crates',
 'Chicken Wire Rolls','Fence Post Caps','Stovepipe Sections','Wash Basin Stands','Latch and Hasp Kits'],
105:['Construction Sand Hoppers','Gravel Aggregate Loads','Cement Powder Sacks','Lumber Plank Lifts','Clay Brick Cubes',
 'Limestone Blocks','Scrap Steel Bales','Pig Iron Ingots','Copper Cathode Sheets','Aluminum Billet Stacks',
 'Raw Cotton Bales','Untreated Hide Bundles','Crude Latex Drums','Wood Pulp Rolls','Glass Cullet Bins',
 'Quartz Sand Silos','Gypsum Board Lifts','Tar Pitch Barrels','Sulfur Prill Sacks','Salt Brine Tanks',
 'Bamboo Cane Bundles','Cork Slab Bales','Hemp Fiber Twists','Wool Clip Sacks','Slate Sheet Pallets',
 'River Stone Crates','Peat Moss Bricks','Charcoal Sack Lots','Coke Breeze Hoppers','Sawdust Compacts',
 'Bitumen Blocks','Kaolin Clay Tubs','Mica Flake Drums','Talc Powder Sacks','Resin Bead Barrels',
 'Soda Ash Totes','Potash Sacks','Lime Slaker Loads','Basalt Fiber Spools','Granite Curb Blanks',
 'Iron Pellet Bins','Foundry Sand Lots','Reclaimed Timber Lifts','Shredded Tire Crumb','Paper Bale Cubes',
 'Plastic Regrind Gaylords','Cullet Glass Sacks','Bone Meal Drums','Ballast Rock Loads','Raw Bauxite Heaps'],
106:['Hematite Rubble Loads','Magnetite Ore Bins','Bauxite Gravel Heaps','Galena Chunk Crates','Sphalerite Lots',
 'Chalcopyrite Rubble','Cassiterite Sands','Pyrite Bulk Bins','Limonite Nodules','Siderite Blocks',
 'Low-Grade Nickel Ore','Cobalt-Bearing Spoil','Manganese Nodule Sacks','Chromite Sand Drums','Ilmenite Beach Sands',
 'Rutile Concentrate Sacks','Wolframite Lumps','Molybdenite Flats','Cinnabar Ore Casks','Stibnite Bundles',
 'Sealed Uraninite Tailings','Monazite Sands','Zircon Gravel Drums','Scheelite Lots','Vanadinite Crates',
 'Asteroid Regolith Bins','Crater Ejecta Loads','Raw Laterite Heaps','Phosphate Rock Lots','Potash Ore Bins',
 'Rock Salt Boulders','Trona Ore Loads','Borax Crusts','Fluorspar Chunks','Barite Lumps',
 'Magnesite Blocks','Dolomite Rubble','Olivine Sands','Anorthite Lunar Spoil','Pallasite Fragments',
 'Carbonaceous Chondrite Bins','Ice-Bound Ore Slurry','Tailings Pond Sludge','Mine-Run Coal Lots','Lignite Bulk Heaps',
 'Anthracite Lumps','Oil Shale Slabs','Gilsonite Chunks','Raw Mica Books','Unsorted Pegmatite'],
11:['Quantum Comm Arrays','Neural Interface Decks','Holo Projector Cores','Grav Sensor Suites','Jump-Calc Coprocessors',
 'Phased Array Antennas','Dense Memory Lattices','Optical Switch Fabrics','Fusion Plant Regulators','Sensor Fusion Hubs',
 'Encrypted Burst Transmitters','Auto-Translator Wands','Targeting Computer Blocks','Inertial Nav Platforms','Deep-Radar Modules',
 'Synthetic Aperture Pods','Bio-Monitor Implant Kits','Adaptive Camo Mesh','EM Shield Generators','Plasma Display Sheets',
 'Smart Dust Canisters','Drone Swarm Brains','Gesture Control Rigs','Retinal HUD Lenses','Cryo-Cooled Processors',
 'Tachyon Pulse Clocks','Self-Healing Circuit Film','Photonic Logic Wafers','Anti-Tamper Vault Chips','Stellar Spectrometer Heads',
 'Gravitic Compensator Chips','Subspace Relay Beacons','Mag-Lock Controller Suites','Hull Stress Telemetry Nets','Fly-By-Light Harnesses',
 'Voice Authentication Slates','Orbital Survey Imagers','Terahertz Scanner Tubes','Quantum Key Vaults','Field-Repair Logic Kits',
 'AI Inference Cards','Superconducting Bus Rails','Emission Masking Coils','Nav Beacon Spoofers','Lab-Grade Signal Forges',
 'Starport Traffic Brains','Vacc-Rated Touch Slates','Hardened Avionics Stacks','Micro-Fusion Power Bricks','Zero-G Assembly Sensors'],
12:['Monofilament Cutter Tools','Memory Metal Frames','Self-Sealing Hull Patches','Vacc-Rated Bearings','Printed Organ Scaffolds',
 'Carbon Weave Panels','Smart Fabric Bolts','Modular Habitat Shells','Aerogel Insulation Blocks','Diamond-Edge Saw Blades',
 'Mag-Lev Rail Segments','Pressure Door Assemblies','Reflec Coating Drums','Variable Visor Plates','Auto-Doc Chassis Kits',
 'Sonic Cleanser Units','Gecko-Grip Sheeting','Powered Exo Frames','Cryo Storage Caskets','Synth-Leather Hides',
 'Nano-Coated Valves','Ballistic Glass Slabs','Fusion Torch Heads','Artificial Gill Packs','Plasteel Plate Lifts',
 'Radiation Wall Tiles','Anti-Static Decking','Hush-Field Door Seals','Smart Hinge Sets','Thermal Superconductor Tape',
 'Vibro-Damped Mounts','Adaptive Wheel Hubs','Crash Foam Canisters','Folding Bridge Trusses','Orbital Tether Links',
 'Self-Tinting Viewports','Mag-Boot Sole Kits','Regenerative Air Scrubbers','Compact Water Reclaimers','Whisper Turbine Blades',
 'Programmable Matter Tiles','Field Forge Anvils','High-G Couch Frames','Sterile Cleanroom Pods','Impact Gel Padding',
 'Laser-Welded Tanks','Glassteel Window Belts','Tuned Mass Dampers','Drop Capsule Shells','Precision Servo Limbs'],
13:['Auto-Plow Rigs','Seed Drone Hives','Hydroponic Rack Systems','Combine Module Heads','Soil Analyzer Wands',
 'Irrigation Pivot Kits','Grain Dryer Towers','Crop Dusting Drones','Greenhouse Dome Kits','Milking Automata',
 'Fence Charger Units','Stump Mulcher Heads','Orchard Ladder Lifts','Bale Wrapper Arms','Compost Reactor Drums',
 'Weather Station Masts','Frost Fan Towers','Sprayer Boom Sets','Harvest Sorter Belts','Egg Incubator Cabinets',
 'Plow Blade Sets','Tiller Tine Crates','Seed Vault Caskets','Drip Line Spools','Grain Auger Tubes',
 'Pasture Seeder Carts','Veterinary Chute Frames','Apiary Frame Kits','Fish Farm Cage Nets','Algae Raceway Liners',
 'Tractor Power Cells','Auto-Feeder Hoppers','Silo Liner Rolls','Root Crop Lifters','Vine Trellis Bundles',
 'Pest Sentry Turrets','Pollinator Drone Swarms','Soil Steamer Carts','Manure Spreader Tanks','Cold Frame Panels',
 'Terraced Field Formers','Windbreak Mesh Rolls','Livestock Tag Guns','Sheep Shear Rigs','Crop Monitor Pylons',
 'Aquaponic Pump Sets','Fruit Press Screws','Grain Mill Stones','Fodder Chopper Drums','Field Kitchen Wagons'],
14:['Cured Grazer Hides','Rendered Tallow Casks','Bone Char Sacks','Wool Fleece Bales','Down Feather Bags',
 'Smoked Game Sides','Salted Fish Barrels','Honeycomb Frames','Beeswax Blocks','Hard Cheese Wheels',
 'Powdered Egg Drums','Gelatin Sheet Cases','Sinew Cord Spools','Horn and Antler Lots','Carved Tusk Substitutes',
 'Leather Strap Coils','Parchment Skins','Lanolin Grease Tubs','Mohair Clip Sacks','Camelid Fiber Bales',
 'Dried Insect Protein','Silk Cocoon Crates','Pearl Oyster Cages','Coral Fragment Bins','Sponge Diver Lots',
 'Fermented Fish Sauce','Aged Sausage Strings','Butter Churn Kegs','Cream Separator Cans','Yogurt Culture Flasks',
 'Reptile Skin Rolls','Feathered Pelt Bundles','Game Trophy Mounts','Silk Thread Cones','Catgut Suture Spools',
 'Ambergris Lumps','Musk Gland Vials','Shell Button Blanks','Tanned Saddle Leather','Rawhide Drum Heads',
 'Marrow Stock Cubes','Blood Meal Sacks','Fish Oil Drums','Leviathan Blubber Casks','Roe Caviar Tins',
 'Milk Protein Powder','Hoof Glue Slabs','Bristle Brush Stock','Carapace Plate Lots','Live Brood Stock Tanks'],
15:['Pre-Stellar Coin Hoards','First Landing Medallions','Vintage Star Charts','Antique Sextant Cases','Imperial Stamp Albums',
 'Ancient Ceramic Urns','Fossil Slab Plates','Meteorite Slice Sets','Old Earth Vinyl Records','Clockwork Automata',
 'Hand-Illuminated Manuscripts','Dueling Pistol Pairs','Ship Christening Plates','War Medal Collections','Signed Holo Stills',
 'Tribal Mask Sets','Jade Figurine Lots','Scrimshaw Carvings','Tapestry Fragments','Reliquary Boxes',
 'Crystal Chess Sets','Music Box Cylinders','Petrified Wood Rounds','Carved Amber Insects','Naval Bell Castings',
 'Explorer Journal Folios','Cartographer Globes','Porcelain Tea Services','Heraldic Banner Rolls','Astrolabe Replicas',
 'Cameo Brooch Trays','Filigree Snuff Boxes','Daguerreotype Plates','Theater Costume Trunks','Royal Seal Matrices',
 'Toy Soldier Armies','Mounted Insect Cabinets','Mineral Specimen Cases','Calligraphy Scroll Tubes','Opera Glass Pairs',
 'Original Captain Logs','Colony Charter Copies','Prototype Gadget Lots','Famous Wreck Salvage','Zero-G Sculpture Mobiles',
 'Vintage Vacc Suit Shells','Race Pennant Flags','Casino Chip Archives','Centennial Whisky Casks','Founder Portrait Oils'],
16:['Mainframe Core Stacks','Workstation Slabs','Server Blade Cases','Data Crystal Racks','Cooling Manifold Kits',
 'Processor Wafer Trays','Memory Lattice Cards','Storage Vault Drives','Backup Tape Silos','Terminal Keyboard Lots',
 'Network Switch Bricks','Fiber Trunk Spools','Firewall Appliance Boxes','Render Farm Nodes','Archive Crystal Vaults',
 'Diagnostic Rig Crates','Dev Board Bundles','Touch Slate Pallets','Docking Cradle Sets','Power Supply Bricks',
 'RAID Cage Frames','Cable Loom Harnesses','Expansion Card Sleeves','Ruggedized Field Decks','Shipboard Compute Cores',
 'Holo Workbench Tables','Print Head Assemblies','Code Vault Tokens','Bio-Lock Keyboards','Cooling Gel Loops',
 'Repair Donor Chassis','Boot ROM Trays','Legacy Port Adapters','Compute Cluster Pods','AI Training Racks',
 'Quantum Annealer Cells','Disk Platter Cases','Heat Sink Pallets','Vibration-Proof Mounts','Operator Chair Consoles',
 'Thin Client Slates','Mesh Node Pucks','Sysadmin Tool Kits','Spare Fan Walls','Cache Module Tubes',
 'Crypto Ledger Boxes','Telemetry Logger Bricks','Sandbox Test Decks','Interface Glove Sets','Refurbished Nav Comps'],
21:['Fire Opal Parcels','Star Sapphire Lots','Raw Diamond Gravel','Emerald Matrix Chunks','Ruby Corundum Nodes',
 'Lattice Quartz Clusters','Piezo Crystal Blanks','Laser-Grade Garnets','Synthetic Spinel Boules','Tourmaline Wands',
 'Amethyst Geode Halves','Topaz Crystal Trays','Peridot Sand Pouches','Zircon Brilliant Lots','Moonstone Cabochons',
 'Black Opal Seams','Chrysoberyl Eyes','Alexandrite Shifts','Aquamarine Prisms','Citrine Points',
 'Iolite Compass Stones','Kunzite Blades','Morganite Hearts','Tanzanite Parcels','Spodumene Logs',
 'Resonant Singing Crystals','Optical Calcite Rhombs','Fluorite Octahedra','Selenite Sword Blades','Celestine Geodes',
 'Labradorite Flash Slabs','Obsidian Mirror Blanks','Jet Mourning Beads','Vacuum-Grown Sapphire Tubes','Data Lattice Seeds',
 'Psionic Focus Shards','Glow Crystal Lamps','Prism Array Blanks','Gem-Cutter Rough Parcels','Heat-Treated Zoisite',
 'Cave Pearl Strings','Bismuth Hopper Crystals','Quartz Timing Blanks','Crystal Chandelier Drops','Druzy Plate Slabs',
 'Nebula Agate Rounds','Chrome Diopside Lots','Padparadscha Parcels','Crystal Skull Curios','Gem Inlay Tesserae'],
22:['Myoelectric Arm Units','Optic Implant Cases','Cochlear Spike Sets','Spinal Shunt Kits','Dermal Plate Sheets',
 'Neural Lace Spools','Synth-Muscle Bundles','Joint Actuator Packs','Subdermal Comm Beads','Reflex Booster Nodes',
 'Artificial Heart Pumps','Lung Scrubber Implants','Kidney Dialysis Pods','Liver Filter Cartridges','Bone Lattice Pins',
 'Finger Tool Tips','Toe Balance Gyros','Retinal Display Films','Voice Box Modulators','Jaw Servo Hinges',
 'Cranial Port Collars','Memory Coprocessor Shards','Pain Editor Modules','Adrenal Governor Chips','Sleep Regulator Discs',
 'Tendon Cable Spools','Knuckle Armor Studs','Palm Mag-Plates','Wrist Rotator Cuffs','Ankle Spring Blades',
 'Thermal Skin Patches','Pressure Sense Meshes','Inner-Ear Balance Kits','Olfactory Booster Pods','Taste Filter Membranes',
 'Charging Spine Rails','Bio-Battery Cells','Coolant Loop Tubing','Diagnostic Socket Caps','Firmware Vault Chips',
 'Limb Mount Couplers','Shoulder Yoke Frames','Hip Gimbal Rings','Cosmetic Shell Panels','Servo Calibration Rigs',
 'Nerve Splice Gel Packs','Implant Sterile Trays','Surgical Install Jigs','Rejection Suppressant Pumps','Spare Knee Assemblies'],
23:['Flash Oven Cabinets','Vat Fryer Stations','Sonic Dishwasher Racks','Bulk Caf Brewers','Nutrient Dispenser Towers',
 'Chill Counter Cases','Carving Station Lamps','Dough Mixer Drums','Proofing Cabinet Shells','Griddle Plate Tops',
 'Soup Kettle Vats','Buffet Rail Sets','Tray Conveyor Belts','Cup Sealer Presses','Portion Scale Decks',
 'Blast Chiller Pods','Ice Maker Bins','Soda Fountain Manifolds','Mess Line Sneeze Guards','Cutlery Sterilizer Tubes',
 'Mobile Galley Carts','Field Canteen Kits','Vacuum Pack Sealers','Spice Carousel Racks','Knife Magnet Bars',
 'Waffle Press Irons','Rotisserie Spit Rigs','Smoothie Turbine Jugs','Meal Tray Stacks','Bain-Marie Inserts',
 'Pizza Stone Decks','Slicer Blade Guards','Mixer Whisk Heads','Pastry Sheet Rollers','Fermentation Crocks',
 'Cold Room Door Kits','Grease Trap Units','Vent Hood Canopies','Allergen Wash Sinks','Menu Board Slates',
 'Tea Urn Samovars','Plate Warmer Lockers','Bar Tap Towers','Keg Coupler Sets','Glass Froster Chests',
 'Server Call Pagers','Takeout Carton Bales','Condiment Pump Banks','Galley Fire Suppressors','Ration Heater Sleeves'],
24:['Foldaway Bunk Frames','Acceleration Couches','Mess Table Flats','Stacking Chair Lots','Stateroom Wardrobes',
 'Zero-G Sleep Sacks','Gimbal Bar Stools','Map Table Cabinets','Locker Bank Units','Captain Desk Sets',
 'Lounge Sofa Modules','Bolt-Down Bed Frames','Holo Table Pedestals','Privacy Screen Panels','Bookshelf Wall Units',
 'Reclining Pilot Chairs','Dining Booth Shells','Footlocker Benches','Hammock Net Rigs','Conference Ring Tables',
 'Child Restraint Seats','Medical Cot Frames','Observation Bay Chaises','Tea House Floor Mats','Ornate Throne Chairs',
 'Wicker Veranda Sets','Carved Headboards','Vanity Mirror Stands','Drafting Stool Lots','Workbench Frames',
 'Cargo Net Seating','Padded Crash Benches','Modular Cubicle Walls','Reading Nook Pods','Bar Counter Sections',
 'Garden Bench Slats','Patio Shade Frames','Nursing Rocker Chairs','Tatami Platform Kits','Four-Poster Kits',
 'Armoire Flat Packs','Sideboard Buffets','Display Case Vitrines','Coat Tree Stands','Umbrella Stand Urns',
 'Futon Roll Bundles','Banquet Trestle Sets','Choir Pew Sections','Barber Chair Units','Lectern Podiums'],
25:['Slot Machine Cabinets','Card Shuffler Decks','Roulette Wheel Crates','Dice Tumbler Cages','Pachinko Banks',
 'Holo Poker Tables','Betting Terminal Slates','Odds Board Displays','Chip Mint Presses','Keno Ball Blowers',
 'Wheel of Fortune Rigs','Craps Table Liners','Baccarat Shoe Sets','Token Changer Consoles','Lottery Drum Spheres',
 'Scratch Card Reels','Race Tote Boards','Bingo Cage Kits','Dart Oddsmaker Boards','Coin Pusher Cabinets',
 'Loaded Dice Detector Wands','Card Marking Scanners','Dealer Visor Kits','Croupier Rake Sets','Cash Cage Drawers',
 'Jackpot Siren Towers','Progressive Meter Signs','Player Card Readers','Chip Tray Carousels','Felt Layout Rolls',
 'Mahjong Tile Cases','Domino Bone Sets','Two-Up Paddle Kits','Sic Bo Shaker Domes','Fan-Tan Bead Bowls',
 'Horse Race Simulators','Fight Pit Betting Boards','Grav-Ball Pool Tables','Dart Drone Targets','Claw Prize Cabinets',
 'VIP Room Door Bells','Security Eye Domes','Counter Surveillance Mirrors','House Edge Calculators','Comp Voucher Printers',
 'Shill Token Bags','Tournament Clock Towers','Bounty Board Slates','Last-Call Bell Kits','Lucky Charm Vending Reels'],
26:['Air/Raft Utility Skiffs','G-Carrier Hulls','Grav Bike Frames','Cargo Float Sleds','Executive Grav Limos',
 'Grav Tractor Units','Survey Skimmer Pods','Ambulance Floaters','Patrol Grav Cutters','Crop Duster Floats',
 'Grav Crane Lifters','Taxi Bubble Cabs','Courier Dart Bikes','Mining Ore Floats','Tour Bus Platforms',
 'Grav Loader Forks','Fire Suppression Floats','Riot Wagon Shells','Luxury Sky Yachts','Racing Grav Sleds',
 'School Transit Floats','Grav Hearse Coaches','Vineyard Row Skimmers','Ranch Herding Bikes','Sky Crane Gantries',
 'Bridge Inspection Pods','Window Washer Floats','Camera Drone Buses','News Van Floaters','Mobile Clinic Pods',
 'Grav Forklift Mules','Dock Tug Floats','Parade Float Chassis','Cold Chain Floaters','Tanker Bladder Sleds',
 'Grav Scooter Lots','Family Wagon Floats','Hunting Blind Skimmers','Glacier Tour Sleds','Dune Hopper Bikes',
 'Canyon Runner Skiffs','Sky Ferry Decks','Pipeline Patrol Floats','Power Line Stringers','Searchlight Pickets',
 'Float Train Cargo Cars','Refueling Bowser Sleds','Med-Evac Stretcher Pods','Survey Mapping Buses','Construction Crew Floats'],
31:['Heirloom Fruit Crates','Fresh Greens Hampers','Root Vegetable Sacks','Cane Sugar Bags','Stone-Ground Flour',
 'Cold-Pressed Oils','Estate Coffee Beans','Mountain Tea Bricks','Wild Honey Jars','Orchard Cider Kegs',
 'Berry Preserve Cases','Pickle Barrel Lots','Artisan Bread Flats','Farm Cheese Rounds','Cream Butter Pats',
 'Free-Range Egg Flats','Smoked Pepper Strings','Dried Mushroom Sacks','Herb Bundle Crates','Sprouting Seed Tins',
 'Cocoa Nib Sacks','Vanilla Pod Tubes','Cinnamon Bark Rolls','Sea Salt Flake Boxes','Spring Water Carboys',
 'Fruit Nectar Flats','Vegetable Stock Tubs','Noodle Nest Cartons','Rice Pearl Sacks','Lentil Mix Bags',
 'Olive Cask Lots','Vinegar Mother Jugs','Yeast Starter Crocks','Maple-Analog Syrup','Jam Sampler Cases',
 'Garden Salsa Jars','Curry Paste Pails','Fermented Bean Cakes','Tofu Press Blocks','Seaweed Sheet Bales',
 'Citrus Crate Lots','Melon Net Sacks','Stone Fruit Trays','Grape Cluster Lugs','Banana-Analog Hands',
 'Frozen Berry Bricks','Juice Concentrate Drums','Granola Bulk Bins','Trail Cracker Cases','Festival Sweet Tins'],
32:['Sonic Laundry Tubs','Auto-Chef Counter Units','Cold Box Refrigerators','Dish Sterilizer Drawers','Air Scrubber Towers',
 'Robo-Vac Discs','Water Heater Cores','Sewing Automata','Bread Former Ovens','Caf Brewer Pots',
 'Garment Presser Frames','Floor Polisher Drums','Window Tint Controllers','Humidity Balancer Pods','Insect Deterrent Posts',
 'Trash Compactor Bins','Garbage Digester Vats','Ice Cream Churners','Juice Extractor Presses','Grain Mill Counters',
 'Sleep Sound Machines','Sun Lamp Panels','Drying Cabinet Racks','Shoe Care Stands','Pet Groomer Pods',
 'Stairlift Rail Kits','Massage Chair Shells','Air Curtain Bars','Heated Towel Racks','Mirror Defogger Films',
 'Wardrobe Refresher Pods','Knife Sharpener Wheels','Vacuum Sealer Stations','Yogurt Culture Pots','Rice Steamer Stacks',
 'Slow Cooker Crocks','Pressure Pot Cookers','Induction Plate Tops','Range Hood Fans','Water Filter Pitchers',
 'Sump Pump Kits','Dehumidifier Drums','Space Heater Coils','Ceiling Fan Sets','Door Chime Consoles',
 'Laundry Fold Arms','Iron Press Boards','Closet Light Strips','Bath Jet Pumps','Kettle Rapid Boilers'],
33:['Arc Welder Cells','Industrial Solvent Drums','Abrasive Grit Hoppers','Cutting Fluid Totes','Electrode Rod Cases',
 'Conveyor Belt Rolls','Pallet Rack Frames','Forklift Battery Packs','Safety Harness Lots','Respirator Cartridge Cases',
 'Hydraulic Fluid Drums','Pneumatic Hose Reels','Bearing Grease Kegs','Machine Anchor Kits','Vibration Pad Mats',
 'Crane Hook Blocks','Chain Hoist Rigs','Rigging Shackle Kegs','Load Strap Bundles','Drum Dolly Frames',
 'Spill Berm Kits','Absorbent Boom Bales','Lockout Tag Stations','Eye Wash Stations','Burn Kit Cabinets',
 'Acetylene Bottle Racks','Oxygen Cylinder Banks','Argon Shield Bottles','Flux Powder Tins','Brazing Alloy Spools',
 'Sandblast Media Sacks','Paint Booth Filters','Powder Coat Hoppers','Anodizing Bath Salts','Pickling Acid Carboys',
 'Quench Oil Drums','Furnace Brick Pallets','Ladle Liner Kits','Mold Release Sprays','Core Sand Binders',
 'Test Gauge Sets','Calibration Weight Cases','Torque Wrench Lockers','Thread Gauge Combs','Surface Plate Slabs',
 'Mill Cutter Trays','Tool Steel Flats','Carbide Insert Boxes','Coolant Pump Skids','Scrap Magnet Plates'],
34:['Vilani Amber Whisky','Frontier Rotgut Casks','Cloudberry Brandy','Glacier Vodka Flats','Smoked Mead Crocks',
 'Hydroponic Hop Ale','Rice Wine Urns','Cactus Spirit Jugs','Honey Liqueur Flasks','Spiced Rum Barrels',
 'Vineyard Reserve Reds','Ice Wine Splits','Sparkling Cider Cases','Plum Wine Carafes','Juniper Gin Crates',
 'Anise Spirit Bottles','Herbal Bitters Cases','Barrel-Proof Bourbon','Peat-Fired Malt Casks','Blue Agave Spirit',
 'Moonshine Mason Lots','Ship Still Ethanol','Monastery Ale Kegs','Abbey Quadrupel Cases','Sour Mash Crocks',
 'Cherry Cordial Flats','Coffee Liqueur Jugs','Cream Liqueur Chests','Pepper Vodka Flights','Sake Cedar Casks',
 'Dreamleaf Cigars','Tabac Twist Bundles','Snuff Tin Cases','Chew Root Plugs','Hookah Resin Bricks',
 'Mild Euphoric Teas','Kava Analog Roots','Betel Quid Packs','Zero-G Vape Pods','Festival Punch Concentrate',
 'Methode Sparkling Bruts','Fortified Port Pipes','Sherry Solera Butts','Absinthe Verte Cases','Grappa Pomace Jugs',
 'Hard Seltzer Flats','Ginger Beer Stone Jars','Mulled Wine Spice Kits','Aperitif Bitters Flights','Captain Reserve Cognac'],
35:['Hand-Rolled Silk Bolts','Estate Perfume Flasks','Gilded Dinner Services','Rare Hardwood Veneers','Designer Gown Trunks',
 'Bespoke Boot Lasts','Jeweled Hair Combs','Platinum Cufflink Sets','Sable-Analog Stoles','Ethical Scrimshaw Lots',
 'Single-Estate Caviar','Truffle Conserve Jars','Vintage Champagne Lots','Aged Balsamic Casks','Gold Leaf Booklets',
 'Crystal Decanter Sets','Marble Statuettes','Cloisonne Vase Pairs','Lacquerware Cabinets','Mother-of-Pearl Inlays',
 'Hand-Knotted Carpets','Tapestry Wall Panels','Calligraphy Ink Stones','First-Edition Folios','Opera Cloak Trunks',
 'Falconry Glove Sets','Polo Saddle Kits','Yacht Brass Fittings','Humidor Cabinets','Meerschaum Pipe Cases',
 'Perfumed Bath Salts','Silk Bed Linens','Cashmere-Analog Throws','Ermine Trim Bundles','Court Jewelry Parures',
 'Enamel Pocket Watches','Conservatory Violins','Grand Piano Actions','Sculpted Chess Sets','Antique Globe Bars',
 'Rare Orchid Bulbs','Bonsai Master Stock','Koi Breeding Pairs','Songbird Aviary Lots','Scented Candle Towers',
 'Artisan Chocolate Slabs','Estate Tea Chests','Reserve Olive Oils','Saffron Thread Vaults','Heirloom Seed Jewels'],
36:['CNC Milling Frames','Fab Printer Gantries','Injection Mold Presses','Vacuum Furnace Shells','Robotic Weld Cells',
 'Stamping Die Sets','Extrusion Screw Barrels','Wire Draw Benches','Pick-and-Place Heads','Wave Solder Tunnels',
 'Pipe Bender Rigs','Sheet Roller Stands','Plasma Cutter Tables','Laser Etch Cabinets','Waterjet Bridge Units',
 'Forge Hammer Frames','Annealing Oven Cars','Casting Carousel Rings','Sand Mold Mixers','Core Shooter Heads',
 'Assembly Line Pallets','Torque Station Arms','Vision Inspection Gates','Conveyor Sorter Spurs','Labeling Print Heads',
 'Bottling Filler Crowns','Cap Torquer Turrets','Blister Pack Formers','Shrink Tunnel Frames','Palletizer Columns',
 'Textile Loom Heads','Knitting Machine Beds','Dye Vat Skids','Calender Roll Stacks','Cut-and-Sew Cells',
 'PCB Etch Lines','Chip Bonder Stages','Cleanroom Air Showers','Wafer Stepper Frames','Reflow Oven Decks',
 'Grain Mill Rollers','Oil Press Expellers','Cannery Retort Vessels','Dairy Pasteurizer Loops','Brewhouse Kettle Skids',
 'Sawmill Head Rigs','Veneer Lathe Beds','Pellet Mill Dies','Glass Blow Molds','Kiln Car Systems'],
41:['Auto-Doc Surgical Pods','Med Scanner Wands','Cryoberth Caskets','Trauma Response Kits','Portable X-Ray Arcs',
 'Dialysis Field Units','Ventilator Cart Sets','Infusion Pump Banks','Defib Paddle Cases','Surgical Laser Pens',
 'Sterile Field Tents','Anesthesia Vapor Carts','Patient Monitor Slates','Diagnostic Bed Frames','Isolation Bubble Kits',
 'Burn Gel Tank Sets','Splint Former Rolls','Traction Frame Kits','Wheelchair Flat Packs','Stretcher Litter Lots',
 'Vaccine Cold Chests','Sample Centrifuges','Microscope Stages','Lab Analyzer Cubes','Blood Bank Fridges',
 'Prosthetic Fitting Jigs','Hearing Test Booths','Vision Lens Kits','Dental Chair Units','Autoclave Drums',
 'Oxygen Concentrators','Suction Pump Kits','Nebulizer Mask Cases','Surgical Tool Trays','Suture Cartridge Boxes',
 'Gene Sequencer Decks','Pathogen Filter Stacks','Quarantine Door Seals','Med Drone Carriers','Telemed Console Slates',
 'Rehab Exo Braces','Hydrotherapy Tubs','UV Sterilizer Arches','Pill Counter Hoppers','Pharmacy Vault Cabinets',
 'Maternity Incubators','Pediatric Scale Sets','Geriatric Lift Hoists','Morgue Drawer Units','Field Hospital Modules'],
42:['Refined Fuel Drums','Lubricant Base Stocks','Paraffin Wax Slabs','Asphalt Binder Totes','Naphtha Carboys',
 'Kerosene Bowsers','Diesel Analog Tanks','Aviation Spirit Kegs','Propane Bottle Racks','Butane Canister Cases',
 'Ethylene Gas Bullets','Propylene Spheres','Sealed Benzene Drums','Toluene Totes','Xylene Carboys',
 'Methanol Tank Skids','Glycol Coolant Drums','Brake Fluid Cases','Transformer Oil Tanks','Hydraulic Oil Totes',
 'White Spirit Cans','Mineral Oil Carboys','Petroleum Jelly Pails','Tar Emulsion Drums','Creosote Casks',
 'Solvent Blend Kegs','Degreaser Concentrate','Mold Oil Drums','Rust Inhibitor Pails','Cutting Oil Barrels',
 'Wax Emulsion Totes','Bitumen Bag Melts','Roofing Pitch Kegs','Carbon Black Sacks','Sulfonate Soap Stocks',
 'Olefin Feedstock Bullets','Aromatic Resin Drums','Plasticizer Totes','Surfactant Pails','Antifreeze Concentrate',
 'Gas Odorant Vials','Refinery Catalyst Drums','Coker Fines Sacks','Slack Wax Slabs','Base Oil Group Lots',
 'Fuel Stabilizer Cases','Octane Booster Flats','Two-Stroke Mix Cans','Bunker Residual Tanks','Lamp Oil Crates'],
43:['Broad-Spectrum Antibiotics','Anti-Rad Dosage Packs','Panimmunity Boosters','Fast-Clot Sprays','Burn Regen Salves',
 'Anagathic Precursor Vials','Vacc Sickness Tablets','Jump Nausea Patches','Sleep Regulator Caps','Medical Stim Autoinjectors',
 'Pain Field Blockers','Fever Breaker Strips','Antiviral Course Packs','Antifungal Creams','Parasite Purge Tonics',
 'Allergy Damper Sprays','Cardiac Support Vials','Insulin Analog Pens','Thyroid Balance Tabs','Bone-Knit Calcium Serums',
 'Nerve Repair Ampoules','Memory Aid Capsules','Focus Enhancer Tabs','Anxiety Damper Drops','Mood Leveler Packs',
 'Vaccine Booster Trays','Sterile Saline Cases','Plasma Expander Bags','Universal Antitoxin Kits','Coagulant Reversal Vials',
 'Anesthetic Vapor Cans','Local Numb Gels','Muscle Relaxant Patches','Anti-Inflammatory Packs','Steroid Taper Kits',
 'Eye Drop Multipacks','Ear Canal Drops','Dermal Repair Films','Scar Reduction Gels','Hair Regrowth Foams',
 'Digestive Enzyme Tabs','Probiotic Culture Vials','Electrolyte Salts','Rehydration Packets','Infant Dose Syrups',
 'Geriatric Tonic Flats','Veterinary Dose Lots','Cryo-Stable Serums','Orphan Cure Lots','Clinical Trial Stock'],
44:['ABS Pellet Gaylords','Polycarbonate Sheets','Nylon Fiber Spools','Aramid Weave Rolls','PTFE Rod Stock',
 'Polyethylene Drums','Polypropylene Sacks','PVC Compound Lots','Acrylic Slab Crates','Silicone Gum Blocks',
 'Epoxy Resin Kits','Urethane Foam Kits','Polyester Chip Sacks','Vinyl Film Rolls','Latex Emulsion Totes',
 'Elastomer O-Ring Stock','Shrink Wrap Spools','Bubble Cushion Rolls','Foam Plank Bundles','Gasket Sheet Lots',
 'Carbon-Fill Compounds','Glass-Fill Granules','UV-Stable Masterbatch','Color Concentrate Bags','Antistatic Pellets',
 'Food-Grade Liners','Medical-Grade Tubing','Conductive Polymer Films','Memory Foam Blocks','Gel Pad Sheets',
 'Filament Printer Spools','Casting Resin Pails','Mold Silicone Kits','Release Film Rolls','Vacuum Bag Film',
 'Composite Prepreg Rolls','Honeycomb Core Panels','Laminate Sheet Lifts','Acetal Bar Stock','PEEK Rod Lots',
 'Biopolymer Pellets','Compostable Film Reels','Recycled Flake Sacks','Polymer Blend Trials','Rubber Crumb Bags',
 'Adhesive Web Rolls','Hot Melt Slats','Sealant Cartridge Cases','Insulation Bead Bags','Geomembrane Rolls'],
45:['Refined Gold Ingots','Fine Silver Bars','Platinum Sponge Jars','Palladium Plate Lots','Rhodium Powder Vials',
 'Iridium Crucible Blanks','Osmium Pellet Flasks','Ruthenium Bar Stock','Electrum Trade Rounds','Gold Dust Pouches',
 'Silver Grain Casks','Mint Coin Blanks','Assay Bead Lots','Bullion Trade Bars','Vault Sealed Kilobars',
 'Gold Wire Spools','Silver Solder Coils','Platinum Lab Crucibles','Gold Leaf Books','Anode Slime Concentrate',
 'Dore Bar Lots','Sponge Iridium Tins','Palladium Catalyst Gauze','Silver Nitrate Crystals','Gold Salt Vials',
 'Jewelry Casting Grain','Dental Alloy Pucks','Mirror Coat Targets','Contact Point Stock','Reflectory Foil Rolls',
 'Numismatic Restrikes','Temple Offering Plates','Ceremonial Torcs','Trade Bangle Bundles','Prospector Nugget Jars',
 'Placer Concentrate Sacks','Black Sand Refinables','Scrap Jewelry Lots','Mine Pour Buttons','Granule Shot Casks',
 'Gold-Filled Rod Stock','Vermeil Blank Trays','Silver Clad Strips','Proof Set Cases','Serialized Bar Registries',
 'Asteroid PGM Concentrate','Refinery Outturn Lots','Good-Delivery Stamps','Sovereign-Type Coins','Karat Scrap Sweeps'],
46:['Enriched Uranium Pellets','Plutonium Oxide Casks','Thorium Sand Drums','Yellowcake Barrels','Reactor Fuel Rod Bundles',
 'Medical Isotope Flasks','Cobalt-60 Source Pigs','Cesium Therapy Capsules','Iridium Weld Sources','Tritium Vial Trays',
 'Radium Legacy Lots','Strontium RTG Cores','Americium Trigger Discs','Polonium Static Strips','Promethium Glow Cells',
 'Calibration Source Sets','Neutron Source Pigs','Depleted Shield Billets','Hot Cell Manipulator Kits','Lead Cask Liners',
 'Isotope Generator Cows','PET Tracer Doses','Brachytherapy Seeds','Gauge Source Holders','Soil Density Sources',
 'Well Logging Sources','Smoke Sensor Sources','Reactor Startup Sources','Licensed Spent Fuel Flasks','Vitrified Waste Logs',
 'MOX Pellet Lots','Fuel Assembly Skeletons','Control Rod Blanks','Heavy Water Drums','Zirconium Clad Tubes',
 'Decay Heat Bricks','RTG Housing Shells','Beta Light Markers','Krypton Lamp Ampoules','Radon Test Canisters',
 'Uranium Glass Cullet','Thoriated Electrode Packs','Monazite Concentrate','Pitchblende Museum Lots','Reactor Coolant Salts',
 'Dosimeter Badge Cases','Survey Meter Kits','Decon Foam Drums','Criticality Spacer Racks','Isotope Transport Casks'],
51:['Cargo Handler Automata','Valet Service Robots','Mining Burrow Drones','Survey Mapper Wings','Sentry Picket Drones',
 'Janitorial Scrub Bots','Window Crawler Units','Agricultural Swarm Kits','Courier Hopper Drones','Inspection Snake Arms',
 'Warehouse Tug Mules','Pallet Shuttle Bots','Inventory Scan Wisps','Dock Welding Spiders','Paint Sprayer Crawlers',
 'Firefighting Tracked Bots','Hazmat Entry Walkers','Search and Rescue Ferrets','Medevac Litter Drones','Police Observation Orbs',
 'Companion Pet Automata','Tutor Homunculus Units','Reception Greeter Shells','Barista Arm Stations','Line Cook Gantries',
 'Nanny Monitor Hovers','Elder Assist Frames','Translator Parrot Drones','Tour Guide Casters','Busker Puppet Rigs',
 'Deep Mine Moles','Pipeline Pig Crawlers','Hull Scraper Limpets','Tank Cleaner Squids','Vent Shaft Spiders',
 'Orbital Tether Climbers','Solar Farm Wipers','Wind Vane Riggers','Buoy Tender Floats','Reef Seeding Turtles',
 'Demolition Breaker Rigs','Rebar Tying Hands','Brick Laying Gantries','Road Painter Carts','Snow Clearing Hounds',
 'Stevedore Lift Frames','Customs Sniffer Hounds','Parade Display Swarms','Camera Gimbal Birds','Spare Chassis Lots'],
52:['Mass Spectrometer Decks','Electron Scope Columns','Gas Chromatograph Racks','Sample Prep Hoods','Cryostat Dewars',
 'Seismic Sensor Strings','Weather Balloon Kits','Telescope Mirror Blanks','Spectrograph Gratings','Particle Counter Wands',
 'Vacuum Chamber Bells','Laser Bench Tables','Optical Flat Sets','Interferometer Rigs','Calorimeter Bombs',
 'Centrifuge Rotor Sets','Incubator Shaker Decks','Autotitrator Stations','pH Probe Cases','Conductivity Cells',
 'Field Assay Kits','Core Sample Drills','Sediment Grab Claws','Plankton Tow Nets','Ice Core Barrels',
 'Geiger Survey Packs','Magnetometer Booms','Gravimeter Spheres','LIDAR Scanner Heads','Sonar Tow Fish',
 'Clean Bench Hoods','Glovebox Isolators','Fume Scrubber Stacks','Reagent Vault Cabinets','Volumetric Glass Sets',
 'Analytical Balance Pods','Microplate Readers','PCR Cycler Blocks','Electrophoresis Tanks','Microtome Blades',
 'Stellar Camera Backs','Radio Dish Feeds','Atmosphere Probe Sondes','Tide Gauge Stations','Strain Gauge Bridges',
 'Wind Tunnel Sections','Shock Tube Segments','High-Speed Camera Rigs','Data Logger Bricks','Standards Reference Sets'],
53:['Filter Mask Cases','Vacc Suit Patch Kits','Emergency Bubble Shelters','Thermal Cocoon Bags','Water Still Kits',
 'Flare Beacon Tubes','Signal Mirror Packs','Storm Tent Bundles','Cold Weather Parkas','Desert Still Suits',
 'Rebreather Scrub Packs','Oxygen Candle Cans','Avalanche Probe Sets','Crevasse Ladder Rolls','Climbing Bolt Racks',
 'Machete Brush Blades','Wire Saw Coils','Fire Steel Strikers','Tinder Cube Tins','Storm Match Vials',
 'Snare Wire Spools','Fishing Yo-Yo Reels','Foraging Field Guides','Iodine Tab Bottles','Charcoal Filter Straws',
 'Snake Bite Suction Kits','Antivenin Field Packs','Insect Net Hoods','Leech Deterrent Salves','Sunburn Barrier Tubs',
 'Glacier Goggle Cases','Whiteout Rope Lines','Marker Panel Tarps','Strobe Rescue Lights','Whistle Lanyard Packs',
 'Paracord Spool Drums','Carabiner Rack Sets','Harness Web Kits','Rappel Brake Bars','Ice Screw Tubes',
 'Life Raft Canisters','Sea Anchor Drogues','Desalinator Hand Pumps','Predator Deterrent Pods','Immersion Suit Bags',
 'Megafauna Spray Cans','Trail Ration Bricks','Hexamine Stove Tabs','Compass Sight Kits','Survival Manual Slates'],
54:['Raw Linen Bolts','Carded Wool Rolls','Denim Yardage Bales','Canvas Duck Rolls','Muslin Bolt Cases',
 'Silk Charmeuse Bolts','Brocade Ribbon Reels','Felt Sheet Stacks','Burlap Sack Cloth','Ticking Stripe Rolls',
 'Flannel Bolt Lots','Corduroy Yardage','Gabardine Suiting','Tweed Bolt Chests','Velvet Pile Rolls',
 'Lace Trim Cards','Embroidery Floss Cones','Quilt Batting Rolls','Upholstery Jacquards','Drapery Sheers',
 'Sailcloth Panels','Tent Fabric Rolls','Awning Stripe Bolts','Tarpaulin Yardage','Cargo Net Webbing',
 'Elastic Band Spools','Zipper Chain Reels','Button Card Cases','Hook Tape Rolls','Thread Cone Crates',
 'Dye Lot Sample Books','Mordant Salt Tins','Batik Wax Blocks','Screen Print Mesh','Loom Heddle Kits',
 'Knit Jersey Tubes','Fleece Roll Bales','Thermal Knit Bolts','Mesh Vent Fabric','Ripstop Nylon Rolls',
 'Ballistic Weave Panels','Fire-Retard Drapes','Antimicrobial Sheets','Conductive Thread Spools','Shade Cloth Rolls',
 'Carpet Loom Yarns','Rug Backing Rolls','Tatami Edge Tape','Banner Vinyl Bolts','Ceremonial Robe Cloth'],
55:['Rare Earth Concentrates','Lanthanum Oxide Drums','Neodymium Billets','Tantalum Capacitor Stock','Niobium Bar Lots',
 'Lithium Brine Salts','Beryllium Copper Rods','Gallium Ingot Flats','Germanium Lens Blanks','Indium Wire Spools',
 'Tellurium Pellet Jars','Selenium Shot Drums','Hafnium Sponge Cans','Zirconium Crystal Bars','Rhenium Pellet Vials',
 'Scandium Master Alloy','Yttrium Oxide Sacks','Cerium Polish Powders','Samarium Magnet Blanks','Dysprosium Lumps',
 'Graphene Sheet Rolls','Carbon Nanotube Yarn','Fullerene Soot Jars','Synthetic Spider Silk','Mycelium Slab Lots',
 'Bio-Resin Casks','Chitin Plate Sheets','Coral-Grown Composites','Kelp Polymer Bales','Living Wood Burls',
 'Volcanic Glass Fibers','Basalt Wool Bats','Pumice Aggregate Sacks','Geothermal Sinter Crusts','Deep Brine Minerals',
 'Aerogel Brick Lots','Foam Metal Billets','Amorphous Alloy Ribbons','Shape-Memory Wire Coils','Superconductor Tape Reels',
 'Isotope-Pure Silicon','Optical Fiber Preforms','Sapphire Boule Blanks','Quartz Crucible Stock','Piezo Ceramic Discs',
 'Catalyst Wash Coats','Zeolite Sieve Drums','Ion Exchange Resins','Heavy Mineral Sands','Cryo-Trapped Noble Gases'],
56:['Tantalite Lode Lots','Columbite Chunks','Spodumene Pegmatite','Lepidolite Books','Petalite Boulders',
 'Beryl Crystal Rough','Chrysoberyl Gravels','Euxenite Lumps','Samarskite Nodules','Gadolinite Pods',
 'Xenotime Sands','Bastnasite Veinstone','Allanite Blocks','Fergusonite Lots','Polycrase Rubble',
 'Pollucite Masses','Zinnwaldite Sheets','Amblygonite Slabs','Triphylite Nodules','Lithiophilite Chunks',
 'Cobaltite Lodes','Skutterudite Druses','Erythrite Blooms','Annabergite Crusts','Gersdorffite Lumps',
 'Platiniferous Chromitite','Osmiridium Placers','Sperrylite Concentrates','Cooperite Lots','Braggite Nodes',
 'Tellurobismuthite Veins','Calaverite Seams','Sylvanite Plates','Petzite Pods','Krennerite Lots',
 'Argentite Masses','Proustite Rubies','Pyrargyrite Crusts','Stephanite Lodes','Polybasite Books',
 'Asteroid Iridium Regolith','Cometary Ice Ores','Exotic Matrix Breccia','Anomalous Magnetic Skarn','Glowing Trace Veinstone',
 'Helium-3 Bearing Regolith','Deuterium Ice Blocks','Stabilized Metallic Hydrogen','Phase-Locked Crystal Ore','Unsorted Xeno-Geode Lots'],
61:['Counterfeit Vintage Wines','Smuggled Imperial Caviar','Forged Master Paintings','Looted Temple Idols','Poached Pelt Bundles',
 'Embargoed Coral Carvings','Black-Market Anagathics','Unlicensed Perfume Clones','Stolen Estate Jewelry','Grave-Robbed Artifacts',
 'Banned Predator Trophies','Counterfeit Designer Trunks','Untaxed Cigar Bales','Bootleg Champagne Lots','Fake Provenance Antiques',
 'Conflict Gem Parcels','Sanctioned-World Silks','Pirated Holo Masters','Knockoff Chronometers','Endangered Orchid Bulbs',
 'Illegal Ivory Tusks','Smuggled Truffle Caches','Duty-Free Overrun Spirits','Replica Crown Regalia','Hot Auction Lots',
 'Laundered Bullion Trinkets','Forbidden Reliquaries','Cloned Celebrity Memorabilia','Contraband Furs','Stolen Manuscript Folios',
 'Off-Books Distillery Casks','Counterfeit Mint Coins','Looted Wreck Treasures','Unregistered Gem Cuts','Smuggler Cellar Reserves',
 'Banned Psion Curios','Restricted Noble Heirlooms','Embargoed Spice Vaults','Black Pearl Strands','Fenced Gallery Pieces',
 'Tax-Stamp Forgeries','Gilded Contraband Cases','Smuggled Saffron Bricks','Counterfeit Estate Teas','Hot Designer Gowns',
 'Unprovenanced Fossils','Restricted Xeno-Curios','Bootleg Anagathic Cosmetics','Forged Signature Instruments','Stolen Vintage Stills'],
62:['Unlicensed Combat Stims','Bootleg Anagathics','Counterfeit Antibiotics','Grey-Lab Psychotropics','Unmarked Sedative Cases',
 'Black Clinic Steroids','Diverted Hospital Opioids','Forged-Label Vaccines','Expired Relabeled Stock','Bathtub Synthase Batches',
 'Mood Slab Pressings','Dream Dust Vials','Glitter Haze Ampoules','Slow Drip Patches','Rage Edge Injectors',
 'Focus Burn Capsules','Night Eye Drops','Deep Sleep Gas Cans','Memory Blur Tabs','Truth Damper Pills',
 'Unlicensed Gene Tonics','Off-Book Fertility Serums','Banned Growth Factors','Smuggled Psi Suppressants','Counterfeit Anti-Rads',
 'Cut-Rate Anesthetics','Diluted Plasma Bags','Mislabeled Cytotoxins','Unscreened Blood Stock','Pirated Drug Formulae',
 'Pop-Up Lab Glassware','Precursor Chemical Casks','Pill Press Die Sets','Capsule Filler Hoppers','Blotter Sheet Reams',
 'Street Dose Bundles','Festival Tab Sheets','Spiked Vape Carts','Laced Chew Plugs','Boosted Energy Shots',
 'Knockoff Anagathic Creams','Underground Trial Lots','Stolen Research Samples','Unethical Booster Courses','Grey Market Nootropics',
 'Smuggler Mule Capsules','Vacuum-Sealed Bricks','Decoy Vitamin Bottles','False-Bottom Med Kits','Counterfeit Pharma Holograms'],
63:['Live Pathogen Cultures','Cloned Tissue Trays','Stem Cell Cryovats','Gene Library Cartridges','Viral Vector Flasks',
 'Prion Sample Pigs','Mutagen Reagent Kits','Banned Embryo Lines','Xeno-Biopsy Cores','Plague Strain Archives',
 'Neurotoxin Reference Vials','Antigen Panel Plates','Gene Splice Kits','Splice Template Spools','Chimera Cell Banks',
 'Organ Printer Bioink','Cadaver Study Lots','Brain Slice Libraries','Spinal Tissue Arrays','Retina Culture Dishes',
 'Telomere Extension Serums','Longevity Trial Samples','Psi-Active Tissue Cores','Symbiote Specimen Jars','Parasite Host Colonies',
 'Zero-G Bone Cultures','Rad-Hardened Cell Lines','Vacuum-Adapted Microbes','Extremophile Slurries','Deep Core Biota',
 'Sealed Biohazard Caskets','Level-4 Sample Pods','Quarantine Specimen Drums','Cold Chain Bio-Flasks','Incubated Egg Racks',
 'Test Subject Records','Anonymized Genome Banks','Tagged Antibody Lots','Isotope-Labeled Tracers','Restricted Enzyme Stocks',
 'Synthetic Womb Prototypes','Neural Organoid Trays','Lab Animal Colonies','Transgenic Seed Lines','Bioreactor Starter Cultures',
 'Pandemic Archive Strains','Forbidden Augment Serums','Unlicensed Vaccine Seeds','Black Lab Notebooks','Sealed Trial Evidence'],
64:['Crated Gauss Rifles','Plasma Gun Pallets','Fusion Charge Packs','Combat Armor Lots','Battle Dress Frames',
 'Grenade Crate Lots','Mortar Tube Sets','Recoilless Rifle Kits','Sniper System Cases','Squad Support Lasers',
 'Tac Missile Canisters','Sandcaster Barrel Loads','Point Defense Mounts','Turret Ring Assemblies','Fire Control Crates',
 'Mine Dispenser Racks','Breaching Charge Kits','Det Cord Spools','Field Artillery Sights','Counter-Battery Radars',
 'Armored Vest Bales','Ballistic Helmet Stacks','Riot Shield Pallets','Stun Baton Cases','Gas Grenade Drums',
 'Night Optic Cases','Thermal Sight Crates','Laser Designator Kits','Encrypted Field Radios','Command Post Tents',
 'Drone Strike Wings','Loitering Munition Tubes','Sentry Gun Tripods','Auto-Turret Brains','IFF Beacon Sets',
 'Field Ration Pallets','Ammo Belt Crates','Magazine Bundle Lots','Reload Press Kits','Armory Rack Systems',
 'Combat Engineer Kits','Bridge-Layer Sections','Fortification Plates','Razor Wire Spools','Bunker Door Sets',
 'Military Med Packs','War Stim Injectors','Camo Net Bales','Decoy Emitter Pods','Surplus Tank Treads'],
65:['Snub Pistol Cases','Auto Pistol Crates','Body Pistol Lots','Revolver Bundle Boxes','Shotgun Rack Lots',
 'Hunting Rifle Crates','Carbine Case Lots','Laser Pistol Cells','Laser Carbine Kits','Stunner Wand Cases',
 'Blade Cutlass Racks','Vibro-Knife Rolls','Boot Dagger Sets','Sword Cane Bundles','Spear Haft Lots',
 'Brass Knuckle Tins','Shock Baton Cases','Whip Coil Bundles','Throwing Blade Sets','Crossbow Limb Kits',
 'Flak Jacket Bales','Mesh Vest Lots','Cloth Armor Bolts','Ablat Panel Stacks','Reflec Suit Rolls',
 'Combat Helm Crates','Visor Faceplate Lots','Greave and Vambrace Sets','Tactical Glove Cases','Armored Boot Pairs',
 'Holster Rig Bundles','Sling and Strap Kits','Ammo Pouch Lots','Speedloader Trays','Cleaning Kit Rolls',
 'Pistol Magazine Crates','Rifle Magazine Lots','Shot Shell Flats','Black Powder Kegs','Percussion Cap Tins',
 'Laser Power Packs','Stun Cartridge Cases','Tranq Dart Tubes','Pepper Fog Canisters','Alarm Pistol Kits',
 'Practice Target Bales','Gun Safe Lockers','Trigger Lock Cases','Range Ear Defenders','Gunsmith Tool Rolls'],
};
function goodVariant(id){ const l=GOODNAMES[id]; return l?l[R(l.length)-1]:((ALLGOODS[id]||{}).name||'Cargo'); }
function goodCat(o){ return o.cat||((ALLGOODS[o.id]||{}).name)||''; }   // old-save fallback
function rollTons(spec){            // "2D6*5", "1D6", "4D6*5" ...
  const m=String(spec).match(/^(\d+)D6(?:\*(\d+))?$/i);
  if(!m)return d6();
  const num=+m[1], mult=m[2]?+m[2]:1; let t=0;
  for(let k=0;k<num;k++)t+=d6();
  return t*mult;
}

// Cepheus Modified Price table, keyed by the 2D6 trade-check result (2- .. 16+)
const PRICE={2:[2.00,0.40],3:[1.80,0.50],4:[1.60,0.60],5:[1.40,0.70],6:[1.20,0.80],
 7:[1.10,0.90],8:[1.00,1.00],9:[0.90,1.10],10:[0.80,1.20],11:[0.70,1.40],
 12:[0.60,1.60],13:[0.50,1.80],14:[0.40,2.00],15:[0.30,3.00],16:[0.20,4.00]};
function priceMult(result,sale){ result=Math.max(2,Math.min(16,Math.round(result))); return PRICE[result][sale?1:0]; }
// Cepheus rule: only the single largest DM in a column applies
const maxDM=(dm,codes)=>codes.reduce((m,c)=>Math.max(m,dm[c]||0),0);

